
[database]
Name = "realworld-dev"
Host = "realworld.cz9z95hgjl9q.ap-northeast-2.rds.amazonaws.com"
Port = 3306
User = "root"
Password = ""

[redis]
Host = "localhost"
Port = 6379
Password = ""
DB = 0
