basePath: /v2
definitions:
  authdto.SignInRequestDTO:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  authdto.SignInResponseDTO:
    properties:
      token:
        type: string
      user_id:
        type: integer
      username:
        type: string
    type: object
  authdto.SignInResponseWrapperDTO:
    properties:
      user:
        $ref: '#/definitions/authdto.SignInResponseDTO'
    type: object
  authdto.SignUpRequestDTO:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - email
    - password
    - username
    type: object
  authdto.SignUpResponseDTO:
    properties:
      email:
        type: string
      user_id:
        type: integer
      username:
        type: string
    type: object
  authdto.SignUpResponseWrapperDTO:
    properties:
      user:
        $ref: '#/definitions/authdto.SignUpResponseDTO'
    type: object
  types.ErrorDetail:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  types.ErrorResponse:
    properties:
      error:
        $ref: '#/definitions/types.ErrorDetail'
    type: object
  userdto.ReadUserProfileResponseDTO:
    properties:
      bio:
        type: string
      profile_image:
        type: string
      username:
        type: string
    type: object
  userdto.ReadUserProfileResponseWrapperDTO:
    properties:
      user:
        $ref: '#/definitions/userdto.ReadUserProfileResponseDTO'
    type: object
  userdto.UpdateUserProfileRequestDTO:
    properties:
      bio:
        type: string
      profile_image:
        type: string
      username:
        type: string
    type: object
  userdto.UpdateUserProfileResponseDTO:
    properties:
      bio:
        type: string
      profile_image:
        type: string
      username:
        type: string
    type: object
  userdto.UpdateUserProfileResponseWrapperDTO:
    properties:
      user:
        $ref: '#/definitions/userdto.UpdateUserProfileResponseDTO'
    type: object
host: petstore.swagger.io
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /user/{user_id}/profile:
    get:
      consumes:
      - application/json
      description: Read user profile
      parameters:
      - description: user_id
        in: path
        name: user_id
        required: true
        type: integer
      - description: jwt token
        in: header
        name: authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/userdto.ReadUserProfileResponseWrapperDTO'
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/types.ErrorResponse'
        "404":
          description: user not found
          schema:
            $ref: '#/definitions/types.ErrorResponse'
        "422":
          description: 요청을 제대로 수행하지 못함
          schema:
            $ref: '#/definitions/types.ErrorResponse'
        "500":
          description: network error
          schema:
            $ref: '#/definitions/types.ErrorResponse'
      summary: Read user profile
      tags:
      - User tag
    put:
      consumes:
      - application/json
      description: Update user profile
      parameters:
      - description: user_id
        in: path
        name: user_id
        required: true
        type: integer
      - description: jwt token
        in: header
        name: authorization
        required: true
        type: string
      - description: updateUserProfileReq
        in: body
        name: updateUserProfileReq
        required: true
        schema:
          $ref: '#/definitions/userdto.UpdateUserProfileRequestDTO'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/userdto.UpdateUserProfileResponseWrapperDTO'
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/types.ErrorResponse'
        "422":
          description: 요청을 제대로 수행하지 못함
          schema:
            $ref: '#/definitions/types.ErrorResponse'
        "500":
          description: network error
          schema:
            $ref: '#/definitions/types.ErrorResponse'
      summary: Update user profile
      tags:
      - User tag
  /user/signin:
    post:
      consumes:
      - application/json
      description: 로그인
      parameters:
      - description: signInReq
        in: body
        name: signInReq
        required: true
        schema:
          $ref: '#/definitions/authdto.SignInRequestDTO'
      produces:
      - application/json
      responses:
        "200":
          description: 로그인 성공
          schema:
            $ref: '#/definitions/authdto.SignInResponseWrapperDTO'
        "400":
          description: 입력값이 유효하지 않음
          schema:
            $ref: '#/definitions/types.ErrorResponse'
        "422":
          description: 유저가 존재하지 않거나 비밀번호가 틀림
          schema:
            $ref: '#/definitions/types.ErrorResponse'
        "500":
          description: network error
          schema:
            $ref: '#/definitions/types.ErrorResponse'
      summary: 로그인
      tags:
      - Auth tag
  /user/signup:
    post:
      consumes:
      - application/json
      description: 회원가입
      parameters:
      - description: signUpReq
        in: body
        name: signUpReq
        required: true
        schema:
          $ref: '#/definitions/authdto.SignUpRequestDTO'
      produces:
      - application/json
      responses:
        "201":
          description: success
          schema:
            $ref: '#/definitions/authdto.SignUpResponseWrapperDTO'
        "400":
          description: 입력값이 유효하지 않음
          schema:
            $ref: '#/definitions/types.ErrorResponse'
        "422":
          description: 이미 존재하는 계정
          schema:
            $ref: '#/definitions/types.ErrorResponse'
      summary: 회원가입
      tags:
      - Auth tag
swagger: "2.0"
